service: notification-center-mail-sender-v2

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  profile: default
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  deploymentBucket:
    # name: 
    serverSideEncryption: AES256 # when using server-side encryption

# The `functions` block defines what code to deploy
functions:
  notifier:
    handler: handler.notifier
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: post
          cors: true
plugins:
  - serverless-offline
